name: cardnest
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  google_mlkit_barcode_scanning: ^0.12.0
  glass: ^2.0.0+1
  barcode_widget: ^2.0.4
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Black.otf
        - asset: fonts/SF-Pro-Display-BlackItalic.otf
        - asset: fonts/SF-Pro-Display-Bold.otf
        - asset: fonts/SF-Pro-Display-BoldItalic.otf
        - asset: fonts/SF-Pro-Display-Heavy.otf
        - asset: fonts/SF-Pro-Display-HeavyItalic.otf
        - asset: fonts/SF-Pro-Display-Light.otf
        - asset: fonts/SF-Pro-Display-LightItalic.otf
        - asset: fonts/SF-Pro-Display-Medium.otf
        - asset: fonts/SF-Pro-Display-MediumItalic.otf
        - asset: fonts/SF-Pro-Display-Regular.otf
        - asset: fonts/SF-Pro-Display-RegularItalic.otf
        - asset: fonts/SF-Pro-Display-Semibold.otf
        - asset: fonts/SF-Pro-Display-SemiboldItalic.otf
        - asset: fonts/SF-Pro-Display-Thin.otf
        - asset: fonts/SF-Pro-Display-ThinItalic.otf
        - asset: fonts/SF-Pro-Display-Ultralight.otf
        - asset: fonts/SF-Pro-Display-UltralightItalic.otf
    - family: SFProRounded
      fonts:
        - asset: fonts/SF-Pro-Rounded-Black.otf
        - asset: fonts/SF-Pro-Rounded-Bold.otf
        - asset: fonts/SF-Pro-Rounded-Heavy.otf
        - asset: fonts/SF-Pro-Rounded-Light.otf
        - asset: fonts/SF-Pro-Rounded-Medium.otf
        - asset: fonts/SF-Pro-Rounded-Regular.otf
        - asset: fonts/SF-Pro-Rounded-Semibold.otf
        - asset: fonts/SF-Pro-Rounded-Thin.otf
        - asset: fonts/SF-Pro-Rounded-Ultralight.otf
